// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKETnZEtDtjCJosS6Yu5GePy734ZNrUMk',
    appId: '1:266791399012:web:86e39fb2cbe97f3283f971',
    messagingSenderId: '266791399012',
    projectId: 'stayfitapp-ca3b2',
    authDomain: 'stayfitapp-ca3b2.firebaseapp.com',
    storageBucket: 'stayfitapp-ca3b2.firebasestorage.app',
    measurementId: 'G-5J9K3Q79LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJAe66CwUVQ99TAdJwsEJUtXe2QZBnY64',
    appId: '1:266791399012:android:6faa450468bb393b83f971',
    messagingSenderId: '266791399012',
    projectId: 'stayfitapp-ca3b2',
    storageBucket: 'stayfitapp-ca3b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyMgsIPPw7VbIRqUxFuGIDUhtTPMTL5ak',
    appId: '1:266791399012:ios:5abc6e3d615aefa583f971',
    messagingSenderId: '266791399012',
    projectId: 'stayfitapp-ca3b2',
    storageBucket: 'stayfitapp-ca3b2.firebasestorage.app',
    iosBundleId: 'com.example.stayFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyMgsIPPw7VbIRqUxFuGIDUhtTPMTL5ak',
    appId: '1:266791399012:ios:5abc6e3d615aefa583f971',
    messagingSenderId: '266791399012',
    projectId: 'stayfitapp-ca3b2',
    storageBucket: 'stayfitapp-ca3b2.firebasestorage.app',
    iosBundleId: 'com.example.stayFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKETnZEtDtjCJosS6Yu5GePy734ZNrUMk',
    appId: '1:266791399012:web:cdeb3d79d19daf8383f971',
    messagingSenderId: '266791399012',
    projectId: 'stayfitapp-ca3b2',
    authDomain: 'stayfitapp-ca3b2.firebaseapp.com',
    storageBucket: 'stayfitapp-ca3b2.firebasestorage.app',
    measurementId: 'G-3R0VC42NXS',
  );

}